blueprint:
  name: Sledování spotřebiče
  description: Vykoná něco, když spotřebič (jako pračka nebo myčka nádobí)
     začal pracovat a poté skončil,na základě sensoru výkonu ve wattech.
  domain: automation
  input:
    power_sensor:
      name: Power Sensor
      description: Entita snímače měřícího výkon ve wattech.
      selector:
        entity:
          domain: sensor
    starting_threshold:
      name: Prahová hodnota startovacího výkonu (1-100W)
      description: Prahová hodnota výkonu, nad kterou předpokládáme, že se spotřebič spustil.
      default: 5
      selector:
        number:
          min: 1.0
          max: 100.0
          unit_of_measurement: W
          mode: slider
          step: 1.0
    starting_hysteresis:
      name: Začátek hysteréze
      description: Doba začátku měření výkonu, která způsobí start skriptu 
        power threshold.
      default: 5
      selector:
        number:
          min: 0.25
          max: 60.0
          unit_of_measurement: min
          mode: slider
          step: 0.25
    finishing_threshold:
      name: Práh spotřeby zajišťující konec
      description: Prahová hodnota výkonu, pod kterou předpokládáme, že spotřebič skončil.
      default: 5
      selector:
        number:
          min: 1.0
          max: 100.0
          unit_of_measurement: W
          mode: slider
          step: 1.0
    finishing_hysteresis:
      name: Konečná hystteréze
      description: Doba trvání měření výkonu, který musí zůstat pod konečnou hodnotou
         aby došlo k ukončení skriptu.
      default: 5
      selector:
        number:
          min: 0.25
          max: 60.0
          unit_of_measurement: min
          mode: slider
          step: 0.25
    actions:
      name: Akce
      description: Akce (např. zaslání notifikace, TTS oznámení, ...)
      selector:
        action: {}
    pre_actions:
      name: Actions
      description: Akce co vykonat, pokud začal skript (např. oznámení, že spotřebič začal pracovat)
      selector:
        action: {}
  source_url: https://raw.githubusercontent.com/GeekOfBohemia/HomeAssistant/main/blueprints/spotrebic/sledovani_spotrebice.yaml
trigger:
- platform: numeric_state
  entity_id: !input 'power_sensor'
  for:
    minutes: !input 'starting_hysteresis'
  above: !input 'starting_threshold'
condition: []
action:
- choose: []
  default: !input 'pre_actions'
- wait_for_trigger:
  - platform: numeric_state
    entity_id: !input 'power_sensor'
    below: !input 'finishing_threshold'
    for:
      minutes: !input 'finishing_hysteresis'
- choose: []
  default: !input 'actions'
mode: single
max_exceeded: silent
